vim.api.nvim_set_hl(0, "TabLine", { ctermfg = 7, ctermbg = "NONE" })
vim.api.nvim_set_hl(0, "Visual", { ctermfg = 0, ctermbg = 4 })
vim.api.nvim_set_hl(0, "Comment", { ctermfg = 7, ctermbg = "NONE" })
vim.api.nvim_set_hl(0, "Type", { ctermfg = 2, ctermbg = "NONE" })
vim.api.nvim_set_hl(0, "Statement", { ctermfg = 5, ctermbg = "NONE" })
vim.api.nvim_set_hl(0, "Function", { ctermfg = 3, ctermbg = "NONE" })
vim.api.nvim_set_hl(0, "Constant", { ctermfg = 4, ctermbg = "NONE" })
vim.api.nvim_set_hl(0, "Identifier", { ctermfg = 6, ctermbg = "NONE" })
vim.api.nvim_set_hl(0, "String", { ctermfg = 1, ctermbg = "NONE" })
vim.api.nvim_set_hl(0, "PreProc", { ctermfg = 4, ctermbg = "NONE" })
vim.api.nvim_set_hl(0, "Directory", { ctermfg = 4, ctermbg = "NONE" })
vim.api.nvim_set_hl(0, "Pmenu", { ctermfg = 0, ctermbg = 4 })
vim.api.nvim_set_hl(0, "PmenuSel", { ctermfg = 0, ctermbg = 6 })
vim.api.nvim_set_hl(0, "Error", { ctermfg = "NONE", ctermbg = "NONE" })
vim.api.nvim_set_hl(0, "Title", { ctermfg = 5, ctermbg = "NONE", bold=true })

vim.api.nvim_set_hl(0, "cTypedef", { ctermfg = 4, ctermbg = "NONE" })
vim.api.nvim_set_hl(0, "cStructure", { ctermfg = 4, ctermbg = "NONE" })
vim.api.nvim_set_hl(0, "cStorageClass", { ctermfg = 4, ctermbg = "NONE" })

vim.api.nvim_set_hl(0, "@variable", { ctermfg = 6, ctermbg = "NONE" })

vim.api.nvim_set_hl(0, "@markup.strong", { ctermfg = 4, ctermbg = "NONE", bold=true })
vim.api.nvim_set_hl(0, "@markup.italic", { ctermfg = 6, ctermbg = "NONE", italic=true })
vim.api.nvim_set_hl(0, "@markup.raw.markdown_inline", { ctermfg = 3, ctermbg = "NONE" })
vim.api.nvim_set_hl(0, "@markup.raw.block.markdown", { ctermfg = 3, ctermbg = "NONE" })
vim.api.nvim_set_hl(0, "@markup.list.markdown", { ctermfg = 7, ctermbg = "NONE" })

vim.api.nvim_set_hl(0, "@lsp.type.typeAlias", { ctermfg = 2, ctermbg = "NONE" })
vim.api.nvim_set_hl(0, "@lsp.type.const", { ctermfg = 4, ctermbg = "NONE" })

vim.api.nvim_set_hl(0, "rustSigil", { ctermfg = 7, ctermbg = "NONE" })
vim.api.nvim_set_hl(0, "rustStorage", { ctermfg = 5, ctermbg = "NONE" })
vim.api.nvim_set_hl(0, "rustLifetime", { ctermfg = 2, ctermbg = "NONE" })

